version: "3.8"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_USER: {{ env.POSTGRES_USER }}
      POSTGRES_PASSWORD: {{ env.POSTGRES_PASSWORD }}
      POSTGRES_DB: {{ env.POSTGRES_DB }}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    restart: always
    command: redis-server --save 60 1 --requirepass {{ env.REDIS_PASSWORD }}
    volumes:
      - redis_data:/data

  nodeserver:
    restart: always
    image: {{ env.API_IMAGE }}
    environment:
      PORT: "2222"
      HOST: "0.0.0.0"
      POSTGRES_USER: {{ env.POSTGRES_USER }}
      POSTGRES_PASSWORD: {{ env.POSTGRES_PASSWORD }}
      POSTGRES_DB: {{ env.POSTGRES_DB }}
      POSTGRES_PORT: {{ env.POSTGRES_PORT }}
      POSTGRES_HOST: {{ env.POSTGRES_HOST }}
      REDIS_PASSWORD: {{ env.REDIS_PASSWORD }}
      REDIS_HOST: {{ env.REDIS_HOST }}
      REDIS_PORT: {{ env.REDIS_PORT }}
      SMTP_USER: {{ env.SMTP_USER }}
      SMTP_PASSWORD: {{ env.SMTP_PASSWORD }}
    depends_on:
      - postgres
      - redis

  nginx:
    restart: always
    image: {{ env.NGINX_IMAGE }}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot_etc:/etc/letsencrypt

volumes:
  postgres_data:
  redis_data:
  certbot_etc:
