version: "3.8"
services:
    nodeserver:
        environment:
            - PORT=2222
        volumes:
            - ./:/app
        build:
            context: ./
        ports:
            - "2222:2222"
