version: "3.8"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_USER: {{ env.POSTGRES_USER }}
      POSTGRES_PASSWORD: {{ env.POSTGRES_PASSWORD }}
      POSTGRES_DB: {{ env.POSTGRES_DB }}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "{{ env.POSTGRES_PORT }}:5432"

  redis:
    image: redis:7.2-alpine
    restart: always
    command: redis-server --save 60 1 --requirepass {{ env.REDIS_PASSWORD }}
    volumes:
      - redis_data:/data
    ports:
      - "{{env.REDIS_PORT}}:6379"

  nodeserver:
    restart: always
    image: {{ env.API_IMAGE }}
    environment:
      - PORT=2222
      - HOST=0.0.0.0
      - POSTGRES_USER={{ env.POSTGRES_USER }}
      - POSTGRES_PASSWORD={{ env.POSTGRES_PASSWORD }}
      - POSTGRES_DB={{ env.POSTGRES_DB }}
      - POSTGRES_PORT={{ env.POSTGRES_PORT }}
      - POSTGRES_HOST={{ env.POSTGRES_HOST }}
      - REDIS_PASSWORD={{ env.REDIS_PASSWORD }}
      - REDIS_HOST={{ env.REDIS_HOST }}
      - REDIS_PORT={{ env.REDIS_PORT }}
    build:
      context: ./
    ports:
      - "2222:2222"
    depends_on:
      - postgres
      - redis
    volumes:
      - nginx:/app/nginx
      - dhparam:/app/dhparam
      - web_root:/app/web-root

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx:/etc/nginx/conf.d
      - dhparam:/etc/ssl/private
      - web_root:/var/www/html
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
    depends_on:
      - nodeserver

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - certbot_etc:/etc/letsencrypt
  #     - certbot_var:/var/lib/letsencrypt
  #     - web_root:/var/www/html
  #   depends_on:
  #     - nginx
  #   command: certonly --webroot --webroot-path=/var/www/html --email hello@wigwam.fun --agree-tos --no-eff-email --staging -d wigwam.fun

volumes:
  postgres_data:
  redis_data:
  certbot_etc:
  certbot_var:
  nginx:
  dhparam:
  web_root:
